### PR TITLE
Optimize storage performance under VirtualBox

### PR DESCRIPTION
**Pull request by wkozaczuk**
Changed hypervisor/vbox/vbox.go by adding "--hostiocache on" option to storagectl
to improve storage performance under VirtualBox. Please see http://underpop.online.fr/v/virtualbox/ch05s07.html for details.

Signed-off-by: Waldemar Kozaczuk <jwkozaczuk@gmail.com>

### CODE REVIEW

**Comment by miha-plesko** [comment]
@wkozaczuk thanks for the contribution. I'm merging this PR without really testing it since we're currently focusing only on `qemu` when using `capstan package compose`. I've just opened an [issue](https://github.com/mikelangelo-project/capstan/issues/68) about this, to remind me that we should support other hypervisors as well.

**Comment by wkozaczuk** [comment]
Actually this change benefits when one runs an image composed by capstan
like so:

capstan run -c 2 -v -p vbox <image>

**Comment by miha-plesko** [comment]
May I ask how do you compose the image that is runnable on vbox? I always use `capstan package compose <image>`, and if I then run it like this `capstan run -p vbox <image>` then it complains that there is no such image...

**Comment by wkozaczuk** [comment]
I simply convert qemu image using qemu-img like so:

qemu-img convert -O vdi ~/.capstan/repository/app/app.qemu
~/.capstan/repository/app/app.vbox

That is enough to make it runnable under VirtualBox.

**Comment by miha-plesko** [comment]
Oh, I didn't realize it's that simple 😄 That just yet another reason why Capstan should be able to do it automatically so users needn't get their hands dirty. Thanks @wkozaczuk !

**Pull request merged**
